# Generated by Django 5.1.5 on 2025-07-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_ai_chatmessage_ai_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ai_chatmessage',
            name='awareness_summary',
        ),
        migrations.RemoveField(
            model_name='ai_chatmessage',
            name='mode',
        ),
        migrations.AddField(
            model_name='ai_chatmessage',
            name='ai_user_summary',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ai_chatmessage',
            name='send_in_mode_c',
            field=models.TextField(default=''),
        ),
    ]
