# Generated by Django 5.1.5 on 2025-06-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_reply_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prompt',
        ),
        migrations.AddField(
            model_name='ai_chatmessage',
            name='room_name',
            field=models.CharField(default='default_room', max_length=100),
        ),
        migrations.AddField(
            model_name='ai_chatmessage_summary',
            name='room_name',
            field=models.CharField(default='default_room', max_length=100),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='room_name',
            field=models.CharField(default='default_room', max_length=100),
        ),
        migrations.AddField(
            model_name='chatmessage_summary',
            name='room_name',
            field=models.CharField(default='default_room', max_length=100),
        ),
    ]
