# Generated by Django 5.1.5 on 2025-07-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_delete_prompt_ai_chatmessage_room_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ai_chatmessage',
            name='ai_user_summary',
        ),
        migrations.RemoveField(
            model_name='ai_chatmessage',
            name='send_in_mode_c',
        ),
        migrations.AddField(
            model_name='ai_chatmessage',
            name='awareness_summary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ai_chatmessage',
            name='mode',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='ai_chatmessage',
            name='ai_message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ai_chatmessage',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ai_chatmessage',
            name='room_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ai_chatmessage',
            name='user_name',
            field=models.CharField(max_length=255),
        ),
    ]
