# Generated by Django 5.1.5 on 2025-07-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_ai_chatmessage_ai_user_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai_chatmessage',
            name='ai_message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ai_chatmessage',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ai_chatmessage',
            name='room_name',
            field=models.CharField(default='default_room', max_length=100),
        ),
        migrations.AlterField(
            model_name='ai_chatmessage',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
    ]
