# Generated by Django 5.1.5 on 2025-07-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_ai_chatmessage_ai_user_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai_chatmessage',
            name='suggestion_response',
            field=models.CharField(blank=True, choices=[('sent', 'Sent'), ('dismissed', 'Dismissed'), ('no_action', 'No Action')], default='no_action', max_length=10),
        ),
    ]
